List defaultCategoryData = [
  {'index':0, 'name': 'Alphabet'},
  {'index':1, 'name': 'Animal Activity Feeding'},
  {'index':2, 'name': 'Animal Activity Grooming'},
  {'index':3, 'name': 'Animal Activity Misc'},
  {'index':4, 'name': 'Animal Birds'},
  {'index':5, 'name': 'Animal Crustacean and Molluscs'},
  {'index':6, 'name': 'Animal Features'},
  {'index':7, 'name': 'Animal Fish and Marine mammals'},
  {'index':8, 'name': 'Animal Habitat'},
  {'index':9, 'name': 'Animal Mammal'},
  {'index':10, 'name': 'Animal Other Invertebrates'},
  {'index':11, 'name': 'Animal Reptiles and Amphibians'},
  {'index':12, 'name': 'Animal Spiders and Insects'},
  {'index':13, 'name': 'Art Colour'},
  {'index':14, 'name': 'Art Making'},
  {'index':15, 'name': 'Building Contents'},
  {'index':16, 'name': 'Building Equipment and devices'},
  {'index':17, 'name': 'Building Furniture'},
  {'index':18, 'name': 'Building Garden and farm'},
  {'index':19, 'name': 'Building Household tasks'},
  {'index':20, 'name': 'Building Office and factory'},
  {'index':21, 'name': 'Building Public'},
  {'index':22, 'name': 'Building Residential'},
  {'index':23, 'name': 'Building School'},
  {'index':24, 'name': 'Building Shop'},
  {'index':25, 'name': 'Building Structure'},
  {'index':26, 'name': 'Celebration Event'},
  {'index':27, 'name': 'Celebration Item'},
  {'index':28, 'name': 'Clothes Accessories'},
  {'index':29, 'name': 'Clothes General'},
  {'index':30, 'name': 'Clothes Jewellery'},
  {'index':31, 'name': 'Clothes Sport'},
  {'index':32, 'name': 'Communication Aid'},
  {'index':33, 'name': 'Communication Conversation'},
  {'index':34, 'name': 'Communication Signs'},
  {'index':35, 'name': 'Computer Icon'},
  {'index':36, 'name': 'Country Flags'},
  {'index':37, 'name': 'Country Maps'},
  {'index':38, 'name': 'Descriptive Direction'},
  {'index':39, 'name': 'Descriptive Position'},
  {'index':40, 'name': 'Descriptive Quantity'},
  {'index':41, 'name': 'Descriptive Shape'},
  {'index':42, 'name': 'Descriptive State'},
  {'index':43, 'name': 'Descriptive Time'},
  {'index':44, 'name': 'Drink Actions'},
  {'index':45, 'name': 'Drink Containers and measures'},
  {'index':46, 'name': 'Drink Description'},
  {'index':47, 'name': 'Drink Type'},
  {'index':48, 'name': 'Electrical Computer'},
  {'index':49, 'name': 'Electrical General'},
  {'index':50, 'name': 'Electrical Media'},
  {'index':51, 'name': 'Electrical Phone'},
  {'index':52, 'name': 'Electrical TV'},
  {'index':53, 'name': 'Environment Weather'},
  {'index':54, 'name': 'Food Breads and baking'},
  {'index':55, 'name': 'Food Dairy'},
  {'index':56, 'name': 'Food Diet'},
  {'index':57, 'name': 'Food Eggs'},
  {'index':58, 'name': 'Food Feeding and eating'},
  {'index':59, 'name': 'Food Festival'},
  {'index':60, 'name': 'Food Fish and seafood'},
  {'index':61, 'name': 'Food Fruit'},
  {'index':62, 'name': 'Food Ingredients'},
  {'index':63, 'name': 'Food Kitchen actions'},
  {'index':64, 'name': 'Food Kitchen items'},
  {'index':65, 'name': 'Food Meals and snacks'},
  {'index':66, 'name': 'Food Meat'},
  {'index':67, 'name': 'Food Nuts'},
  {'index':68, 'name': 'Food Pastas and rice'},
  {'index':69, 'name': 'Food Poultry'},
  {'index':70, 'name': 'Food Sweets and desserts'},
  {'index':71, 'name': 'Food Vegetables and salad'},
  {'index':72, 'name': 'Food Vegetables and salads'},
  {'index':73, 'name': 'Healthcare Body parts'},
  {'index':74, 'name': 'Healthcare Grooming activities'},
  {'index':75, 'name': 'Healthcare Grooming items'},
  {'index':76, 'name': 'Healthcare Medical conditions'},
  {'index':77, 'name': 'Healthcare Medical items'},
  {'index':78, 'name': 'Holiday and travel'},
  {'index':79, 'name': 'Leisure Games'},
  {'index':80, 'name': 'Leisure General'},
  {'index':81, 'name': 'Leisure Playground'},
  {'index':82, 'name': 'Leisure Toys'},
  {'index':83, 'name': 'Military'},
  {'index':84, 'name': 'Money'},
  {'index':85, 'name': 'Music Instrument'},
  {'index':86, 'name': 'Number'},
  {'index':87, 'name': 'Number Activity'},
  {'index':88, 'name': 'People Actions'},
  {'index':89, 'name': 'People Descriptive'},
  {'index':90, 'name': 'People Feelings'},
  {'index':91, 'name': 'People Profession'},
  {'index':92, 'name': 'People Relationship'},
  {'index':93, 'name': 'Plants and Trees'},
  {'index':94, 'name': 'Politics'},
  {'index':95, 'name': 'Question'},
  {'index':96, 'name': 'Religion Festival'},
  {'index':97, 'name': 'Religion General'},
  {'index':98, 'name': 'Religion Person'},
  {'index':99, 'name': 'Science'},
  {'index':100, 'name': 'Science Astronomy'},
  {'index':101, 'name': 'Science Eco'},
  {'index':102, 'name': 'Sport'},
  {'index':103, 'name': 'Sport Accessories'},
  {'index':104, 'name': 'Tools Actions'},
  {'index':105, 'name': 'Tools Garden'},
  {'index':106, 'name': 'Tools Workshop'},
  {'index':107, 'name': 'Transport Air'},
  {'index':108, 'name': 'Transport Rail'},
  {'index':109, 'name': 'Transport Road'},
  {'index':110, 'name': 'Transport Space'},
  {'index':111, 'name': 'Transport Water'},
  {'index':112, 'name': 'Work and School Education'},
  {'index':113, 'name': 'Work and School Stationery'},
  {'index':114, 'name': 'Work and School Subjects'},
  {'index':115, 'name': 'Work and School Timetable'},
];