List defaultCategoryData = [
  {'categoryIndex':0, 'symbolName': 'Alphabet'},
  {'categoryIndex':1, 'symbolName': 'Animal Activity Feeding'},
  {'categoryIndex':2, 'symbolName': 'Animal Activity Grooming'},
  {'categoryIndex':3, 'symbolName': 'Animal Activity Misc'},
  {'categoryIndex':4, 'symbolName': 'Animal Birds'},
  {'categoryIndex':5, 'symbolName': 'Animal Crustacean and Molluscs'},
  {'categoryIndex':6, 'symbolName': 'Animal Features'},
  {'categoryIndex':7, 'symbolName': 'Animal Fish and Marine mammals'},
  {'categoryIndex':8, 'symbolName': 'Animal Habitat'},
  {'categoryIndex':9, 'symbolName': 'Animal Mammal'},
  {'categoryIndex':10, 'symbolName': 'Animal Other Invertebrates'},
  {'categoryIndex':11, 'symbolName': 'Animal Reptiles and Amphibians'},
  {'categoryIndex':12, 'symbolName': 'Animal Spiders and Insects'},
  {'categoryIndex':13, 'symbolName': 'Art Colour'},
  {'categoryIndex':14, 'symbolName': 'Art Making'},
  {'categoryIndex':15, 'symbolName': 'Building Contents'},
  {'categoryIndex':16, 'symbolName': 'Building Equipment and devices'},
  {'categoryIndex':17, 'symbolName': 'Building Furniture'},
  {'categoryIndex':18, 'symbolName': 'Building Garden and farm'},
  {'categoryIndex':19, 'symbolName': 'Building Household tasks'},
  {'categoryIndex':20, 'symbolName': 'Building Office and factory'},
  {'categoryIndex':21, 'symbolName': 'Building Public'},
  {'categoryIndex':22, 'symbolName': 'Building Residential'},
  {'categoryIndex':23, 'symbolName': 'Building School'},
  {'categoryIndex':24, 'symbolName': 'Building Shop'},
  {'categoryIndex':25, 'symbolName': 'Building Structure'},
  {'categoryIndex':26, 'symbolName': 'Celebration Event'},
  {'categoryIndex':27, 'symbolName': 'Celebration Item'},
  {'categoryIndex':28, 'symbolName': 'Clothes Accessories'},
  {'categoryIndex':29, 'symbolName': 'Clothes General'},
  {'categoryIndex':30, 'symbolName': 'Clothes Jewellery'},
  {'categoryIndex':31, 'symbolName': 'Clothes Sport'},
  {'categoryIndex':32, 'symbolName': 'Communication Aid'},
  {'categoryIndex':33, 'symbolName': 'Communication Conversation'},
  {'categoryIndex':34, 'symbolName': 'Communication Signs'},
  {'categoryIndex':35, 'symbolName': 'Computer Icon'},
  {'categoryIndex':36, 'symbolName': 'Country Flags'},
  {'categoryIndex':37, 'symbolName': 'Country Maps'},
  {'categoryIndex':38, 'symbolName': 'Descriptive Direction'},
  {'categoryIndex':39, 'symbolName': 'Descriptive Position'},
  {'categoryIndex':40, 'symbolName': 'Descriptive Quantity'},
  {'categoryIndex':41, 'symbolName': 'Descriptive Shape'},
  {'categoryIndex':42, 'symbolName': 'Descriptive State'},
  {'categoryIndex':43, 'symbolName': 'Descriptive Time'},
  {'categoryIndex':44, 'symbolName': 'Drink Actions'},
  {'categoryIndex':45, 'symbolName': 'Drink Containers and measures'},
  {'categoryIndex':46, 'symbolName': 'Drink Description'},
  {'categoryIndex':47, 'symbolName': 'Drink Type'},
  {'categoryIndex':48, 'symbolName': 'Electrical Computer'},
  {'categoryIndex':49, 'symbolName': 'Electrical General'},
  {'categoryIndex':50, 'symbolName': 'Electrical Media'},
  {'categoryIndex':51, 'symbolName': 'Electrical Phone'},
  {'categoryIndex':52, 'symbolName': 'Electrical TV'},
  {'categoryIndex':53, 'symbolName': 'Environment Weather'},
  {'categoryIndex':54, 'symbolName': 'Food Breads and baking'},
  {'categoryIndex':55, 'symbolName': 'Food Dairy'},
  {'categoryIndex':56, 'symbolName': 'Food Diet'},
  {'categoryIndex':57, 'symbolName': 'Food Eggs'},
  {'categoryIndex':58, 'symbolName': 'Food Feeding and eating'},
  {'categoryIndex':59, 'symbolName': 'Food Festival'},
  {'categoryIndex':60, 'symbolName': 'Food Fish and seafood'},
  {'categoryIndex':61, 'symbolName': 'Food Fruit'},
  {'categoryIndex':62, 'symbolName': 'Food Ingredients'},
  {'categoryIndex':63, 'symbolName': 'Food Kitchen actions'},
  {'categoryIndex':64, 'symbolName': 'Food Kitchen items'},
  {'categoryIndex':65, 'symbolName': 'Food Meals and snacks'},
  {'categoryIndex':66, 'symbolName': 'Food Meat'},
  {'categoryIndex':67, 'symbolName': 'Food Nuts'},
  {'categoryIndex':68, 'symbolName': 'Food Pastas and rice'},
  {'categoryIndex':69, 'symbolName': 'Food Poultry'},
  {'categoryIndex':70, 'symbolName': 'Food Sweets and desserts'},
  {'categoryIndex':71, 'symbolName': 'Food Vegetables and salad'},
  {'categoryIndex':72, 'symbolName': 'Food Vegetables and salads'},
  {'categoryIndex':73, 'symbolName': 'Healthcare Body parts'},
  {'categoryIndex':74, 'symbolName': 'Healthcare Grooming activities'},
  {'categoryIndex':75, 'symbolName': 'Healthcare Grooming items'},
  {'categoryIndex':76, 'symbolName': 'Healthcare Medical conditions'},
  {'categoryIndex':77, 'symbolName': 'Healthcare Medical items'},
  {'categoryIndex':78, 'symbolName': 'Holiday and travel'},
  {'categoryIndex':79, 'symbolName': 'Leisure Games'},
  {'categoryIndex':80, 'symbolName': 'Leisure General'},
  {'categoryIndex':81, 'symbolName': 'Leisure Playground'},
  {'categoryIndex':82, 'symbolName': 'Leisure Toys'},
  {'categoryIndex':83, 'symbolName': 'Military'},
  {'categoryIndex':84, 'symbolName': 'Money'},
  {'categoryIndex':85, 'symbolName': 'Music Instrument'},
  {'categoryIndex':86, 'symbolName': 'Number'},
  {'categoryIndex':87, 'symbolName': 'Number Activity'},
  {'categoryIndex':88, 'symbolName': 'People Actions'},
  {'categoryIndex':89, 'symbolName': 'People Descriptive'},
  {'categoryIndex':90, 'symbolName': 'People Feelings'},
  {'categoryIndex':91, 'symbolName': 'People Profession'},
  {'categoryIndex':92, 'symbolName': 'People Relationship'},
  {'categoryIndex':93, 'symbolName': 'Plants and Trees'},
  {'categoryIndex':94, 'symbolName': 'Politics'},
  {'categoryIndex':95, 'symbolName': 'Question'},
  {'categoryIndex':96, 'symbolName': 'Religion Festival'},
  {'categoryIndex':97, 'symbolName': 'Religion General'},
  {'categoryIndex':98, 'symbolName': 'Religion Person'},
  {'categoryIndex':99, 'symbolName': 'Science'},
  {'categoryIndex':100, 'symbolName': 'Science Astronomy'},
  {'categoryIndex':101, 'symbolName': 'Science Eco'},
  {'categoryIndex':102, 'symbolName': 'Sport'},
  {'categoryIndex':103, 'symbolName': 'Sport Accessories'},
  {'categoryIndex':104, 'symbolName': 'Tools Actions'},
  {'categoryIndex':105, 'symbolName': 'Tools Garden'},
  {'categoryIndex':106, 'symbolName': 'Tools Workshop'},
  {'categoryIndex':107, 'symbolName': 'Transport Air'},
  {'categoryIndex':108, 'symbolName': 'Transport Rail'},
  {'categoryIndex':109, 'symbolName': 'Transport Road'},
  {'categoryIndex':110, 'symbolName': 'Transport Space'},
  {'categoryIndex':111, 'symbolName': 'Transport Water'},
  {'categoryIndex':112, 'symbolName': 'Work and School Education'},
  {'categoryIndex':113, 'symbolName': 'Work and School Stationery'},
  {'categoryIndex':114, 'symbolName': 'Work and School Subjects'},
  {'categoryIndex':115, 'symbolName': 'Work and School Timetable'},
];